BtgMyBudgetBundle_homepage:
    path:  /hello/{name}
    controller: Btg\MyBudgetBundle\Controller\DefaultController::index
    methods: GET|HEAD

BtgMyBudgetBundle_reports:
  pattern: /budget/reports
  defaults: { _controller: Btg\MyBudgetBundle:Reports:numeric }
  
BtgMyBudgetBundle_help_notes:
  pattern: /budget/help/notes
  defaults: { _controller: Btg\MyBudgetBundle:Help:notes }
    
BtgMyBudgetBundle_help:
  pattern: /budget/help
  defaults: { _controller: Btg\MyBudgetBundle:Import:help }
  
BtgMyBudgetBundle_import:
  pattern: /budget/import
  defaults: { _controller: Btg\MyBudgetBundle:Import:process }

BtgMyBudgetBundle_categories:
  pattern: /budget/categories
  defaults: { _controller: Btg\MyBudgetBundle:Category:categories }
  
BtgMyBudgetBundle_matches:
  pattern: /budget/matches
  defaults: { _controller: Btg\MyBudgetBundle:Matches:matches }
  
BtgMyBudgetBundle_options:
  pattern: /budget/options
  defaults: { _controller: Btg\MyBudgetBundle:Options:edit }
  
BtgMyBudgetBundle_transactions:
  pattern: /budget/transactions
  defaults: { _controller: Btg\MyBudgetBundle:Transaction:transactions }
